{{- $Values := .Values.exporter }}
{{- $Clusters := .Values.es_clusters }}
{{- range $i, $es := $Clusters}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "es-monitor.fullname" $ }}-exporter-{{ lower $es.name }}
  labels:
    esCluster: {{ lower $es.name }}
    app: exporter
    {{- include "es-monitor.labels" $ | nindent 4 }}
spec:
  replicas: {{ $Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: exporter
      esCluster: {{ lower $es.name }}
      {{- include "es-monitor.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: exporter
        esCluster: {{ lower $es.name }}
        {{- include "es-monitor.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "es-monitor.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}-{{ lower $es.name }}
          securityContext:
            {{- toYaml $Values.securityContext | nindent 12 }}
          image: "{{ $Values.image.repository }}:{{ $Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $Values.image.pullPolicy }}
          command:
            - /bin/elasticsearch_exporter
            - --es.uri={{ $es.url }}
            # - --es.ca=/etc/certificates/ca.crt
            - --es.all
            - --log.format=logfmt
            - --log.level=info
            - --es.indices
            - --es.indices_settings
            - --es.indices_mappings
            - --es.shards
            - --es.snapshots
            - --es.cluster_settings
            - --es.clusterinfo.interval={{ $es.interval | default "5s" }}
            - --es.timeout={{ $es.timeout | default "5s" }}
            {{- if $es.skipSsl }}
            - --es.ssl-skip-verify
            {{- end }}
          ports:
            - name: http
              containerPort: 9114
              protocol: TCP
          env:
            - name: ES_USERNAME
              value: {{ $es.username }}
            - name: ES_PASSWORD
              value: {{ $es.password }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9114
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {{- toYaml $Values.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/ash", "-c", "sleep 20"]
      {{- with $Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}