{{- $Values := .Values.exporter }}
{{- $Clusters := .Values.esClusters }}
{{- range $i, $es := $Clusters}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-monitor.fullname" $ }}-exporter-{{ lower $es.name }}
  labels:
    esCluster: {{ lower $es.name }}
    app: exporter
    {{- include "es-monitor.labels" $ | nindent 4 }}
spec:
  type: {{ $Values.service.type }}
  ports:
    - port: {{ $Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    esCluster: {{ lower $es.name }}
    app: exporter
    {{- include "es-monitor.selectorLabels" $ | nindent 4 }}
{{- end }}