apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-monitor.fullname" . }}-prometheus
  labels:
    app: prometheus
    {{- include "es-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: prometheus
    {{- include "es-monitor.selectorLabels" . | nindent 4 }}
