apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-ns.fullname" . }}-server-conf
  labels:
    {{- include "prometheus-ns.labels" . | nindent 4 }}
data:
  prometheus.rules: |-
    groups:
      - name: elasticsearch
        rules:
          - record: elasticsearch_filesystem_data_used_percent
            expr: 100 * (elasticsearch_filesystem_data_size_bytes - elasticsearch_filesystem_data_free_bytes)
              / elasticsearch_filesystem_data_size_bytes
          - record: elasticsearch_filesystem_data_free_percent
            expr: 100 - elasticsearch_filesystem_data_used_percent
          - alert: ElasticsearchTooFewNodesRunning
            expr: elasticsearch_cluster_health_number_of_nodes < 3
            for: 5m
            labels:
              severity: critical
            annotations:
              description: There are only {{ printf "{{ $value }}" }} < 3 Elasticsearch nodes running
              summary: Elasticsearch running on less than 3 nodes
          - alert: ElasticsearchHeapTooHigh
            expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}
              > 0.9
            for: 15m
            labels:
              severity: critical
            annotations:
              description: The heap usage is over 90% for 15m
              summary: Elasticsearch node {{ printf "{{ $labels.node }}" }} heap usage is high
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers: []
    scrape_configs:
      - job_name: elastic-stack
        static_configs:
          - targets: ['es-exporter:9114']