{{- if and .Values.prometheus.enabled .Values.prometheus.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-monitor.fullname" . }}-grafana
  labels:
    app: grafana
    {{- include "es-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.grafana.service.type }}
  ports:
    - port: {{ .Values.prometheus.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: grafana
    {{- include "es-monitor.selectorLabels" . | nindent 4 }}
{{- end }}
