{{- if .Values.metricbeat.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "es-monitor.fullname" . }}-metricbeat-config
  labels:
    app: metricbeat
    {{- include "es-monitor.labels" . | nindent 4 }}
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      path: /usr/share/metricbeat/modules.d/*.yaml
      reload.enabled: false
    processors:
      - add_cloud_metadata:
    output.elasticsearch:
      hosts: ["{{ .Values.metricbeat.output.elasticsearch.host | default "elasticsearch" }}:{{ .Values.metricbeat.output.elasticsearch.port | default "9200" }}"]
      username: "{{ .Values.metricbeat.output.elasticsearch.username | default "elastic" }}"
      password: "{{ .Values.metricbeat.output.elasticsearch.password | default "password" }}"
      {{- if .Values.metricbeat.output.elasticsearch.skipSsl }}
      ssl:
        verification_mode: "none"
      {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "es-monitor.fullname" . }}-metricbeat-modules
  labels:
    app: metricbeat
    {{- include "es-monitor.labels" . | nindent 4 }}
data:
  prometheus.yaml: |-
    {{- $Clusters := .Values.es_clusters }}
    {{- range $i, $es := $Clusters}}
    - module: prometheus
      enabled: true
      hosts: ['{{ include "es-monitor.fullname" $ }}-exporter-{{ lower $es.name }}:9114']
      metrics_path: /metrics
    {{- end }}
{{- end }}
