{{- if .Values.output.elasticsearch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "es-monitor.fullname" . }}-metricbeat-config
  labels:
    app: metricbeat
    {{- include "es-monitor.labels" . | nindent 4 }}
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      path: /usr/share/metricbeat/modules.d/*.yaml
      reload.enabled: false
    processors:
      - add_cloud_metadata:
    output.logstash:
      hosts: ["{{ include "es-monitor.fullname" . }}-logstash:5044"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "es-monitor.fullname" . }}-metricbeat-modules
  labels:
    app: metricbeat
    {{- include "es-monitor.labels" . | nindent 4 }}
data:
  prometheus.yaml: |-
    {{- $Clusters := .Values.esClusters }}
    {{- range $i, $es := $Clusters}}
    - module: prometheus
      enabled: true
      hosts: ['{{ include "es-monitor.fullname" $ }}-exporter-{{ lower $es.name }}:9114']
      metrics_path: /metrics
    {{- end }}
{{- end }}
