# Default values for es-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

esClusters:
  - name: evega-local
    url: https://es.jackson.com
    username: elastic
    password: "L436edHEi5955bbN9a1k8vNs"
    skipSsl: true
  - name: evega-global
    url: https://es.evega.co.in
    username: elastic
    password: "L436edHEi5955bbN9a1k8vNs"
    skipSsl: false
    interval: 30s
    timeout: 30s
output:
  prometheus:
    enabled: false
  elasticsearch:
    enabled: true
    host: https://es.jackson.com
    port: 443
    username: elastic
    password: "L436edHEi5955bbN9a1k8vNs"
    skipSsl: true
indexMapper:
  - indexPatterns:
      - twitter-*
      - es-monitoring-*
    fields:
      owner: "Pankaj"
      project: "Development"
  - indexPatterns:
      - http-input-*
    fields:
      owner: "Pankaj"
      project: "Web Ingested"
grafana:
  enabled: false
  service:
    type: LoadBalancer
    port: 80