# Default values for es-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

esClusters:
  - name: evega-local
    url: https://es.jackson.com
    username: elastic
    password: "L436edHEi5955bbN9a1k8vNs"
    skipSsl: true
  - name: evega-global
    url: https://es.evega.co.in
    username: elastic
    password: "L436edHEi5955bbN9a1k8vNs"
    skipSsl: false
    interval: 30s
    timeout: 30s
output:
  prometheus:
    enabled: false
  elasticsearch:
    enabled: true
    host: https://es.jackson.com
    port: 443
    username: elastic
    password: "L436edHEi5955bbN9a1k8vNs"
    skipSsl: true
exporter:
  metrics:
    all: false
    cluster_settings: false
    indices: true
    indices_settings: false
    indices_mappings: false
    aliases: false
    shards: false
    snapshots: false
    slm: false
    data_stream: false
indexMapper:
  - indexPatterns:
      - es-monitoring-*
    fields:
      owner: "Pankaj"
      project: "Development"
  - indexPatterns:
      - http-input-*
    fields:
      owner: "Dips"
      project: "Web Ingested"
  - indexPatterns:
      - twitter-*
    fields:
      owner: "Dips"
      project: "Development"
  - indexPatterns:
      - prometheus-*
    fields:
      owner: "Pankaj"
      project: "Monitoring"
grafana:
  enabled: false
  service:
    type: LoadBalancer
    port: 80