{{- if .Values.logstash.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "es-monitor.fullname" . }}-logstash
  labels:
    app: "logstash"
    {{- include "es-monitor.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "es-monitor.fullname" . }}-logstash
  replicas: {{ .Values.logstash.replicaCount }}
  selector:
    matchLabels:
      app: "logstash"
      {{- include "es-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/logstash/configmap.yaml") . | sha256sum }}
      {{- with .Values.logstash.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "logstash"
        {{- include "es-monitor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "es-monitor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.logstash.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ include "es-monitor.fullname" . }}-logstash
          securityContext:
            {{- toYaml .Values.logstash.securityContext | nindent 12 }}
          image: "{{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.logstash.image.pullPolicy }}
          ports:
            - name: ls-service
              containerPort: 9600
            - name: beats
              containerPort: 5044
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: ls-service
            initialDelaySeconds: 30
            periodSeconds: 60
          livenessProbe:
            tcpSocket:
              port: ls-service
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: pipeline-config
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: pipelines.yml
            - name: prometheus-config
              mountPath: /usr/share/logstash/pipeline/prometheus
          resources:
            {{- toYaml .Values.logstash.resources | nindent 12 }}
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-pipeline
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: pipeline-config
        configMap:
          name: logstash-pipeline
          items:
            - key: pipelines.yml
              path: pipelines.yml
      - name: prometheus-config
        configMap:
          name: logstash-pipeline
          items:
            - key: prometheus.conf
              path: prometheus.conf
{{- end }}